### ISSUE TITLE
GetUsers erroring out

### ISSUE THREAD

**Issue by ivucica** [ssttevee/go-wordpress#1]
Hi,

```
Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'DBNAMEHERE.um.meta_value' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group
```

Do I have a duplicate record with `meta_key = "description"` (or any other dupe)? No:

```
mysql> select meta_key, count(*) as c from wp_usermeta where user_id = 1 group by meta_key having c > 1;
Empty set (0.00 sec)
```

---

I have prepared a patch, but unfortunately I am unable to contribute it back (or, actually, use this useful and interesting project) without a `LICENSE` file allowing me to do so. Would you mind adding a license?

Something like Apache 2, MIT, BSD or even GPL/LGPL (which are pretty much functionally equivalent for almost all Go code) would be ideal and allow me to send this.

(On the other hand, the patch is really just a oneliner adding `um.meta_value` to the `GroupBy`.)

**Comment by ssttevee** [comment]
I've added a license for you.

I don't seem to be getting the same error. What version of mysql are you using? All of my testing was done on version 5.7.14.

**Comment by ivucica** [comment]
It's 5.7.18:

```
$ apt-cache policy mysql-server
mysql-server:
  Installed: 5.7.18-1
  Candidate: 5.7.18-1
  Version table:
 *** 5.7.18-1 100
        100 /var/lib/dpkg/status
     5.5.9999+default 950
        950 http://ftp.nl.debian.org/debian stretch/main amd64 Packages
     5.5.60-0+deb8u1 500
        500 http://ftp.nl.debian.org/debian jessie/main amd64 Packages
        500 http://ftp.nl.debian.org/debian jessie/main i386 Packages
```

I can't tell what could be the problem; my guess is it should be something in the query, not in the database, but I can't really tell how to fix it in the schema.
